
services:
  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - flight_management_network

  # Next.js application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://127.0.0.1:27017/flights?authSource=admin
    depends_on:
      - mongo
    networks:
      - flight_management_network

networks:
  flight_management_network:
    driver: bridge

volumes:
  mongo_data:
